### ISSUE TITLE
Results different on mobile

### ISSUE THREAD

**Issue by loythegreat** [rizz-wan/betterwordle#1]
When using mobile browsers, the solver gives inaccurate results.

For example, when I type "D" in the Have Letters field, it doesn't show any results in Possible Words.

And when I type "L" in the Doesn't Have Letters field, it still shows results with the letter "L" in Possible Words.

**Comment by rizz-wan** [comment]
Hi @loythegreat, thanks for reaching out, might be an intermittent issue, not able to reproduce the issue on my side. Tried one wordle and works fine.
![image](https://github.com/rizz-wan/betterwordle/assets/39019270/2603084a-537e-4a1d-9fc3-766e0d569a5b)
![image](https://github.com/rizz-wan/betterwordle/assets/39019270/0454d7be-db44-4885-b143-a4812b4d344c)
Do make sure to have a look at the [caveats](https://github.com/rizz-wan/betterwordle#caveat)
Thanks
